<?php defined('KeramikGuardian') or die();

/**
 * Keramik Terminologie Editor
 * Copyright (C) 2012-2013  Bernhard R. Arnold
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

class MunsellSoilColors {

	public $dict = array(
		'white' => 'weiß',
		'light greenish gray' => 'hellgrau',
		'pale green' => 'grünlich',
		'light gray' => 'hellgrau',
		'gray' => 'mittelgrau',
		'greenish gray' => 'mittelgrau',
		'grayish green' => 'grünlich',
		'dark gray' => 'dunkelgrau',
		'dark greenish gray' => 'dunkelgrau',
		'very dark gray' => 'dunkelgrau',
		'very dark greenish gray' => 'dunkelgrau',
		'very dark grayish green' => 'dunkelgrün',
		'black' => 'schwarz',
		'greenish black' => 'schwarz',
		'light bluish gray' => 'hellgrau',
		'bluish gray' => 'mittelgrau',
		'dark bluish gray' => 'dunkelgrau',
		'very dark bluish gray' => 'dunkelgrau',
		'bluish black' => 'schwarz',
		'pinkish white' => 'weiß',
		'pink' => 'beige',
		'pale red' => 'rötlich',
		'light red' => 'rötlich',
		'reddish gray' => 'mittelgrau',
		'weak red' => 'mittelrot',
		'red' => 'mittelrot',
		'dark reddish gray' => 'dunkelgrau',
		'dusky red' => 'mittelrot',
		'dark red' => 'dunkelrot',
		'reddish black' => 'schwarz',
		'very dusky red' => 'dunkelrot',
		'light reddish gray' => 'hellgrau',
		'light reddish brown' => 'hellbraun',
		'reddish brown' => 'mittelbraun',
		'dark reddish brown' => 'dunkelbraun',
		'pinkish gray' => 'mittelgrau',
		'reddish yellow' => 'beige',
		'yellowish red' => 'mittelrot',
		'light brown' => 'hellbraun',
		'brown' => 'mittelbraun',
		'strong brown' => 'dunkelbraun',
		'dark brown' => 'dunkelbraun',
		'very dark brown' => 'dunkelbraun',
		'very pale brown' => 'hellbraun',
		'yellow' => 'beige',
		'light brownish gray' => 'hellgrau',
		'pale brown' => 'hellbraun',
		'light yellowish brown' => 'hellbraun',
		'brownish yellow' => 'beige',
		'grayish brown' => 'mittelbraun',
		'yellowish brown' => 'mittelbraun',
		'dark grayish brown' => 'dunkelbraun',
		'dark yellowish brown' => 'dunkelbraun',
		'very dark grayish brown' => 'dunkelbraun',
		'pale yellow' => 'hellbeige',
		'light bownish gray' => 'hellgrau',
		'olive yellow' => 'beige',
		'light olive brown' => 'hellbraun',
		'olive brown' => 'mittelbraun',
		'dark olive brown' => 'dunkelbraun',
		'light olive gray' => 'hellgrau',
		'pale olive' => 'helloliv',
		'olive gray' => 'olivgrau',
		'olive' => 'oliv',
		'dark olive gray' => 'dunkelgrau',

			);

	private $colors = array(
		'GLEY1' => array(
			array('N 8/', '#cbcbcb', 'white'),
			array('10Y 8/1', '#CFCDBC', 'light greenish gray'),
			array('5GY 8/1', '#C9CCBA', 'light greenish gray'),
			array('10GY 8/1', '#C5D0C2', 'light greenish gray'),
			array('5G 8/1', '#C0CEC4', 'light greenish gray'),
			array('5G 8/2', '#B7D1BF', 'pale green'),
			array('N 7/', '#b3b3b3', 'light gray'),
			array('10Y 7/1', '#B2B0A2', 'light greenish gray'),
			array('5GY 7/1', '#B1B4A0', 'light greenish gray'),
			array('10GY 7/1', '#A8B2A5', 'light greenish gray'),
			array('5G 7/1', '#A8B6A9', 'light greenish gray'),
			array('5G 7/2', '#9EB6A5', 'pale green'),
			array('N 6/', '#969696', 'gray'),
			array('10Y 6/1', '#949384', 'greenish gray'),
			array('5GY 6/1', '#95978A', 'greenish gray'),
			array('10GY 6/1', '#909A8D', 'greenish gray'),
			array('5G 6/1', '#8B968D', 'greenish gray'),
			array('5G 6/2', '#839A8C', 'pale green'),
			array('N 5/', '#767676', 'gray'),
			array('10Y 5/1', '#7B7A6C', 'greenish gray'),
			array('5GY 5/1', '#74786B', 'greenish gray'),
			array('10GY 5/1', '#757E75', 'greenish gray'),
			array('5G 5/1', '#6F7A73', 'greenish gray'),
			array('5G 5/2', '#677D70', 'grayish green'),
			array('N 4/', '#616161', 'dark gray'),
			array('10Y 4/1', '#646257', 'dark greenish gray'),
			array('5GY 4/1', '#5C6154', 'dark greenish gray'),
			array('10GY 4/1', '#5A6258', 'dark greenish gray'),
			array('5G 4/1', '#59665C', 'dark greenish gray'),
			array('5G 4/2', '#4E6457', 'grayish green'),
			array('N 3/', '#464646', 'very dark gray'),
			array('10Y 3/1', '#48483D', 'very dark greenish gray'),
			array('5GY 3/1', '#464941', 'very dark greenish gray'),
			array('10GY 3/1', '#444A42', 'very dark greenish gray'),
			array('5G 3/1', '#424D46', 'very dark greenish gray'),
			array('5G 3/2', '#3C4D45', 'very dark grayish green'),
			array('N 2.5/', '#3b3b3b', 'black'),
			array('10Y 2.5/1', '#2F2F25', 'greenish black'),
			array('5GY 2.5/1', '#30332D', 'greenish black'),
			array('10GY 2.5/1', '#2E322E', 'greenish black'),
			array('5G 2.5/1', '#2B332D', 'greenish black'),
			array('5G 2.5/2', '#26332A', 'very dark grayish green'),
		),
		'GLEY2' => array(
			array('10G 8/1', '#BFCFC8', 'light greenish gray'),
			array('5BG 8/1', '#BCCCC7', 'light greenish gray'),
			array('10BG 8/1', '#C2D1D0', 'light greenish gray'),
			array('5B 8/1', '#C0CDCD', 'light bluish gray'),
			array('10B 8/1', '#C0C9CC', 'light bluish gray'),
			array('5PB 8/1', '#C8CCCE', 'light bluish gray'),
			array('10G 7/1', '#A6B5AD', 'light greenish gray'),
			array('5BG 7/1', '#A6B3AF', 'light greenish gray'),
			array('10BG 7/1', '#A6B5B5', 'light greenish gray'),
			array('5B 7/1', '#A8B5B4', 'light bluish gray'),
			array('10B 7/1', '#AAB2B5', 'light bluish gray'),
			array('5PB 7/1', '#ABB0B4', 'light bluish gray'),
			array('10G 6/1', '#8A9890', 'greenish gray'),
			array('5BG 6/1', '#8A9691', 'greenish gray'),
			array('10BG 6/1', '#8C9B9A', 'greenish gray'),
			array('5B 6/1', '#8C9697', 'bluish gray'),
			array('10B 6/1', '#8C9496', 'bluish gray'),
			array('5PB 6/1', '#929599', 'bluish gray'),
			array('10G 5/1', '#727E78', 'greenish gray'),
			array('5BG 5/1', '#727E7C', 'greenish gray'),
			array('10BG 5/1', '#707C7C', 'greenish gray'),
			array('5B 5/1', '#6E787A', 'bluish gray'),
			array('10B 5/1', '#525A5E', 'bluish gray'),
			array('5PB 5/1', '#767C81', 'bluish gray'),
			array('10G 4/1', '#57635E', 'dark greenish gray'),
			array('5BG 4/1', '#5A6460', 'dark greenish gray'),
			array('10BG 4/1', '#576363', 'dark greenish gray'),
			array('5B 4/1', '#596468', 'dark bluish gray'),
			array('10B 4/1', '#727A7E', 'dark bluish gray'),
			array('5PB 4/1', '#5F6368', 'dark bluish gray'),
			array('10G 3/1', '#414A47', 'very dark greenish gray'),
			array('5BG 3/1', '#404A48', 'very dark greenish gray'),
			array('10BG 3/1', '#3D4848', 'very dark greenish gray'),
			array('5B 3/1', '#3D4A4D', 'very dark bluish gray'),
			array('10B 3/1', '#3E474B', 'very dark bluish gray'),
			array('5PB 3/1', '#44484F', 'very dark bluish gray'),
			array('10G 2.5/1', '#2B3431', 'greenish black'),
			array('5BG 2.5/1', '#2A3432', 'greenish black'),
			array('10BG 2.5/1', '#2B3436', 'greenish black'),
			array('5B 2.5/1', '#2E363A', 'bluish black'),
			array('10B 2.5/1', '#2A3338', 'bluish black'),
			array('5PB 2.5/1', '#2E3238', 'bluish black'),
		),
		'10R' => array(
			array('10R 8/1', '#', 'white'),
			array('10R 8/2', '#', 'pinkish white'),
			array('10R 8/3', '#', 'pink'),
			array('10R 8/4', '#', 'pink'),
			array('10R 7/1', '#', 'light gray'),
			array('10R 7/2', '#', 'pale red'),
			array('10R 7/3', '#', 'pale red'),
			array('10R 7/4', '#', 'pale red'),
			array('10R 7/6', '#', 'light red'),
			array('10R 7/8', '#', 'light red'),
			array('10R 6/1', '#', 'reddish gray'),
			array('10R 6/2', '#', 'pale red'),
			array('10R 6/3', '#', 'pale red'),
			array('10R 6/4', '#', 'pale red'),
			array('10R 6/6', '#', 'light red'),
			array('10R 6/8', '#', 'light red'),
			array('10R 5/1', '#', 'reddish gray'),
			array('10R 5/2', '#', 'weak red'),
			array('10R 5/3', '#', 'weak red'),
			array('10R 5/4', '#', 'weak red'),
			array('10R 5/6', '#', 'red'),
			array('10R 5/8', '#', 'red'),
			array('10R 4/1', '#', 'dark reddish gray'),
			array('10R 4/2', '#', 'weak red'),
			array('10R 4/3', '#', 'weak red'),
			array('10R 4/4', '#', 'weak red'),
			array('10R 4/6', '#', 'red'),
			array('10R 4/8', '#', 'red'),
			array('10R 3/1', '#', 'dark reddish gray'),
			array('10R 3/2', '#', 'dusky red'),
			array('10R 3/3', '#', 'dusky red'),
			array('10R 3/4', '#', 'dusky red'),
			array('10R 3/6', '#', 'dark red'),
			array('10R 2.5/1', '#', 'reddish black'),
			array('10R 2.5/2', '#', 'very dusky red'),
		),
		'2.5YR' => array(
			array('2.5R 8/1', '#F4E5E4', 'white'),
			array('2.5R 8/2', '#F4E5E4', 'pinkish white'),
			array('2.5R 8/3', '#EEC5C3', 'pink'),
			array('2.5R 8/4', '#EEC5C3', 'pink'),
			array('2.5R 7/1', '#', 'light reddish gray'),
			array('2.5R 7/2', '#', 'pale red'),
			array('2.5R 7/3', '#', 'light reddish brown'),
			array('2.5R 7/4', '#', 'light reddish brown'),
			array('2.5R 7/6', '#', 'light red'),
			array('2.5R 7/8', '#', 'light red'),
			array('2.5R 6/1', '#', 'reddish gray'),
			array('2.5R 6/2', '#', 'pale red'),
			array('2.5R 6/3', '#', 'light reddish brown'),
			array('2.5R 6/4', '#', 'light reddish brown'),
			array('2.5R 6/6', '#', 'light red'),
			array('2.5R 6/8', '#', 'light red'),
			array('2.5R 5/1', '#', 'reddish gray'),
			array('2.5R 5/2', '#', 'weak red'),
			array('2.5R 5/3', '#', 'reddish brown'),
			array('2.5R 5/4', '#', 'reddish brown'),
			array('2.5R 5/6', '#', 'red'),
			array('2.5R 5/8', '#', 'red'),
			array('2.5R 4/1', '#', 'dark reddish gray'),
			array('2.5R 4/2', '#', 'weak red'),
			array('2.5R 4/3', '#', 'reddish brown'),
			array('2.5R 4/4', '#', 'reddish brown'),
			array('2.5R 4/6', '#', 'red'),
			array('2.5R 4/8', '#', 'red'),
			array('2.5R 3/1', '#', 'dark reddish gray'),
			array('2.5R 3/2', '#', 'dusky red'),
			array('2.5R 3/3', '#', 'dark reddish brown'),
			array('2.5R 3/4', '#', 'dark reddish brown'),
			array('2.5R 3/6', '#', 'dark red'),
			array('2.5R 2.5/1', '#', 'reddish black'),
			array('2.5R 2.5/2', '#', 'very dusky red'),
			array('2.5R 2.5/3', '#', 'dark reddish brown'),
			array('2.5R 2.5/4', '#', 'dark reddish brown'),
		),
		'5YR' => array(
			array('5YR 8/1', '#', 'white'),
			array('5YR 8/2', '#', 'pinkish white'),
			array('5YR 8/3', '#', 'pink'),
			array('5YR 8/4', '#', 'pink'),
			array('5YR 7/1', '#', 'light gray'),
			array('5YR 7/2', '#', 'pinkish gray'),
			array('5YR 7/3', '#', 'pink'),
			array('5YR 7/4', '#', 'pink'),
			array('5YR 7/6', '#', 'reddish yellow'),
			array('5YR 7/8', '#', 'reddish yellow'),
			array('5YR 6/1', '#', 'gray'),
			array('5YR 6/2', '#', 'pinkish gray'),
			array('5YR 6/3', '#', 'light reddish brown'),
			array('5YR 6/4', '#', 'light reddish brown'),
			array('5YR 6/6', '#', 'reddish yellow'),
			array('5YR 6/8', '#', 'reddish yellow'),
			array('5YR 5/1', '#', 'gray'),
			array('5YR 5/2', '#', 'reddish gray'),
			array('5YR 5/3', '#', 'reddish brown'),
			array('5YR 5/4', '#', 'reddish brown'),
			array('5YR 5/6', '#', 'yellowish red'),
			array('5YR 5/8', '#', 'yellowish red'),
			array('5YR 4/1', '#', 'dark gray'),
			array('5YR 4/2', '#', 'dark reddish gray'),
			array('5YR 4/3', '#', 'reddish brown'),
			array('5YR 4/4', '#', 'reddish brown'),
			array('5YR 4/6', '#', 'yellowish red'),
			array('5YR 3/1', '#', 'very dark gray'),
			array('5YR 3/2', '#', 'dark reddish brown'),
			array('5YR 3/3', '#', 'dark reddish brown'),
			array('5YR 3/4', '#', 'dark reddish brown'),
			array('5YR 2.5/1', '#', 'black'),
			array('5YR 2.5/2', '#', 'dark reddish brown'),
		),
		'7.5YR' => array(
			array('7.5YR 8/1', '#', 'white'),
			array('7.5YR 8/2', '#', 'pinkish white'),
			array('7.5YR 8/3', '#', 'pink'),
			array('7.5YR 8/4', '#', 'pink'),
			array('7.5YR 8/6', '#', 'reddish yellow'),
			array('7.5YR 7/1', '#', 'light gray'),
			array('7.5YR 7/2', '#', 'pinkish gray'),
			array('7.5YR 7/3', '#', 'pink'),
			array('7.5YR 7/4', '#', 'pink'),
			array('7.5YR 7/6', '#', 'reddish yellow'),
			array('7.5YR 7/8', '#', 'reddish yellow'),
			array('7.5YR 6/1', '#', 'gray'),
			array('7.5YR 6/2', '#', 'pinkish gray'),
			array('7.5YR 6/3', '#', 'light brown'),
			array('7.5YR 6/4', '#', 'light brown'),
			array('7.5YR 6/6', '#', 'reddish yellow'),
			array('7.5YR 6/8', '#', 'reddish yellow'),
			array('7.5YR 5/1', '#', 'gray'),
			array('7.5YR 5/2', '#', 'brown'),
			array('7.5YR 5/3', '#', 'brown'),
			array('7.5YR 5/4', '#', 'brown'),
			array('7.5YR 5/6', '#', 'strong brown'),
			array('7.5YR 5/8', '#', 'strong brown'),
			array('7.5YR 4/1', '#', 'dark gray'),
			array('7.5YR 4/2', '#', 'brown'),
			array('7.5YR 4/3', '#', 'brown'),
			array('7.5YR 4/4', '#', 'brown'),
			array('7.5YR 4/6', '#', 'strong brown'),
			array('7.5YR 3/1', '#', 'very dark gray'),
			array('7.5YR 3/2', '#', 'dark brown'),
			array('7.5YR 3/3', '#', 'dark brown'),
			array('7.5YR 3/4', '#', 'dark brown'),
			array('7.5YR 2.5/1', '#', 'black'),
			array('7.5YR 2.5/2', '#', 'very dark brown'),
			array('7.5YR 2.5/3', '#', 'very dark brown'),
		),
		'10YR' => array(
			array('10YR 8/1', '#', 'white'),
			array('10YR 8/2', '#', 'very pale brown'),
			array('10YR 8/3', '#', 'very pale brown'),
			array('10YR 8/4', '#', 'very pale brown'),
			array('10YR 8/6', '#', 'yellow'),
			array('10YR 8/8', '#', 'yellow'),
			array('10YR 7/1', '#', 'light gray'),
			array('10YR 7/2', '#', 'light gray'),
			array('10YR 7/3', '#', 'very pale brown'),
			array('10YR 7/4', '#', 'very pale brown'),
			array('10YR 7/6', '#', 'yellow'),
			array('10YR 7/8', '#', 'yellow'),
			array('10YR 6/1', '#', 'gray'),
			array('10YR 6/2', '#', 'light brownish gray'),
			array('10YR 6/3', '#', 'pale brown'),
			array('10YR 6/4', '#', 'light yellowish brown'),
			array('10YR 6/6', '#', 'brownish yellow'),
			array('10YR 6/8', '#', 'brownish yellow'),
			array('10YR 5/1', '#', 'gray'),
			array('10YR 5/2', '#', 'grayish brown'),
			array('10YR 5/3', '#', 'brown'),
			array('10YR 5/4', '#', 'yellowish brown'),
			array('10YR 5/6', '#', 'yellowish brown'),
			array('10YR 5/8', '#', 'yellowish brown'),
			array('10YR 4/1', '#', 'dark gray'),
			array('10YR 4/2', '#', 'dark grayish brown'),
			array('10YR 4/3', '#', 'brown'),
			array('10YR 4/4', '#', 'dark yellowish brown'),
			array('10YR 4/6', '#', 'dark yellowish brown'),
			array('10YR 3/1', '#', 'very dark gray'),
			array('10YR 3/2', '#', 'very dark grayish brown'),
			array('10YR 3/3', '#', 'dark brown'),
			array('10YR 3/4', '#', 'dark yellowish brown'),
			array('10YR 3/6', '#', 'dark yellowish brown'),
			array('10YR 2.5/1', '#', 'black'),
			array('10YR 2.5/2', '#', 'very dark brown'),
		),
		'2.5Y' => array(
			array('2.5Y 8/1', '#', 'white'),
			array('2.5Y 8/2', '#', 'pale yellow'),
			array('2.5Y 8/3', '#', 'pale yellow'),
			array('2.5Y 8/4', '#', 'pale yellow'),
			array('2.5Y 8/6', '#', 'yellow'),
			array('2.5Y 8/8', '#', 'yellow'),
			array('2.5Y 7/1', '#', 'light gray'),
			array('2.5Y 7/2', '#', 'light gray'),
			array('2.5Y 7/3', '#', 'pale yellow'),
			array('2.5Y 7/4', '#', 'pale yellow'),
			array('2.5Y 7/6', '#', 'yellow'),
			array('2.5Y 7/8', '#', 'yellow'),
			array('2.5Y 6/1', '#', 'gray'),
			array('2.5Y 6/2', '#', 'light bownish gray'),
			array('2.5Y 6/3', '#', 'light yellowish brown'),
			array('2.5Y 6/4', '#', 'light yellowish brown'),
			array('2.5Y 6/6', '#', 'olive yellow'),
			array('2.5Y 6/8', '#', 'olive yellow'),
			array('2.5Y 5/1', '#', 'gray'),
			array('2.5Y 5/2', '#', 'grayish brown'),
			array('2.5Y 5/3', '#', 'light olive brown'),
			array('2.5Y 5/4', '#', 'light olive brown'),
			array('2.5Y 5/6', '#', 'light olive brown'),
			array('2.5Y 4/1', '#', 'dark gray'),
			array('2.5Y 4/2', '#', 'dark grayish brown'),
			array('2.5Y 4/3', '#', 'olive brown'),
			array('2.5Y 4/4', '#', 'olive brown'),
			array('2.5Y 3/1', '#', 'very dark gray'),
			array('2.5Y 3/2', '#', 'very dark grayish brown'),
			array('2.5Y 3/3', '#', 'dark olive brown'),
			array('2.5Y 2.5/1', '#', 'black'),
		),
		'5Y' => array(
			array('5Y 8/1', '#', 'white'),
			array('5Y 8/2', '#', 'pale yellow'),
			array('5Y 8/3', '#', 'pale yellow'),
			array('5Y 8/4', '#', 'pale yellow'),
			array('5Y 8/6', '#', 'yellow'),
			array('5Y 8/8', '#', 'yellow'),
			array('5Y 7/1', '#', 'light gray'),
			array('5Y 7/2', '#', 'light gray'),
			array('5Y 7/3', '#', 'pale yellow'),
			array('5Y 7/4', '#', 'pale yellow'),
			array('5Y 7/6', '#', 'yellow'),
			array('5Y 7/8', '#', 'yellow'),
			array('5Y 6/1', '#', 'gray'),
			array('5Y 6/2', '#', 'light olive gray'),
			array('5Y 6/3', '#', 'pale olive'),
			array('5Y 6/4', '#', 'pale olive'),
			array('5Y 6/6', '#', 'olive yellow'),
			array('5Y 6/8', '#', 'olive yellow'),
			array('5Y 5/1', '#', 'gray'),
			array('5Y 5/2', '#', 'olive gray'),
			array('5Y 5/3', '#', 'olive'),
			array('5Y 5/4', '#', 'olive'),
			array('5Y 5/6', '#', 'olive'),
			array('5Y 4/1', '#', 'dark gray'),
			array('5Y 4/2', '#', 'olive gray'),
			array('5Y 4/3', '#', 'olive'),
			array('5Y 4/4', '#', 'olive'),
			array('5Y 3/1', '#', 'very dark gray'),
			array('5Y 3/2', '#', 'dark olive gray'),
			array('5Y 2.5/1', '#', 'black'),
			array('5Y 2.5/2', '#', 'black'),
		),
	);

	public function __construct() {
	}

	public function getName($code) {
		foreach ($this->colors as $key => &$table) {
			foreach ($table as &$color) {
				if ($color[0] == $code)
					return $color[2];
			}
		}
		return '';
	}

	public function getTranslation($name) {
		if (array_key_exists($name, $this->dict))
			return $this->dict[$name];
		return '';
	}

	public function getHtml($name) {
		$html = "<select name=\"{$name}\">".PHP_EOL;
		$html .= '<option value="">keine Angabe</option>';
		foreach ($this->colors as $key => &$table) {
			$html .= "<optgroup label=\"{$key}\">".PHP_EOL;
			foreach ($table as &$color) {
				$selected = (isset($_POST[$name]) and $_POST[$name] == $color[0]) ? ' selected' : '';
				$html .= "<option style=\"color:{$color[1]};\" value=\"{$color[0]}\"{$selected}>&#x2588;&#x2588; {$color[0]} ({$color[2]})</option>".PHP_EOL;
			}
			$html .= '</optgroup>'.PHP_EOL;
		}
		$html .= '</select>'.PHP_EOL;
		return $html;
	}
}
